# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60d124b5496382f60b5c4ca1d3fe1b18a63b86af29c5c485ccae8d90c85995c5160f133a6883c074e2c7080477dbbe6afe772f7cd4492021b02cdbbb7331639

test:
  secret_key_base: ee063d0f3067dece16468f99b6819e342d34fefcd5eb35432e17db0e066d80fc4d11a02cd72a4c05ba01750806056d22b9d8deb3db1dcb0c8272543b232f3c45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
